export enum ExpressionAbbreviation {
  eq = 'eq',
  neq = 'neq',
  lt = 'lt',
  lte = 'lte',
  gt = 'gt',
  gte = 'gte',
  plus = 'plus',
  minus = 'minus',
  mul = 'mul',
  div = 'div',
  mod = 'mod',
  and = 'and',
  or = 'or',
  not = 'not',
  assign = 'assign',
  plus_assign = 'plus_assign',
  minus_assign = 'minus_assign',
  mul_assign = 'mul_assign',
  div_assign = 'div_assign',
  mod_assign = 'mod_assign',
}

export const mappings = {
  [ExpressionAbbreviation.eq]: '=',
  [ExpressionAbbreviation.neq]: '!=',
  [ExpressionAbbreviation.lt]: '<',
  [ExpressionAbbreviation.lte]: '<=',
  [ExpressionAbbreviation.gt]: '>',
  [ExpressionAbbreviation.gte]: '>=',
  [ExpressionAbbreviation.plus]: '+',
  [ExpressionAbbreviation.minus]: '-',
  [ExpressionAbbreviation.mul]: '*',
  [ExpressionAbbreviation.div]: '/',
  [ExpressionAbbreviation.mod]: '%',
  [ExpressionAbbreviation.and]: '&&',
  [ExpressionAbbreviation.or]: '||',
  [ExpressionAbbreviation.not]: '!',
  [ExpressionAbbreviation.assign]: '=',
  [ExpressionAbbreviation.plus_assign]: '+=',
  [ExpressionAbbreviation.minus_assign]: '-=',
  [ExpressionAbbreviation.mul_assign]: '*=',
  [ExpressionAbbreviation.div_assign]: '/=',
  [ExpressionAbbreviation.mod_assign]: '%=',
};
